CREATE EXTENSION IF NOT EXISTS postgis;

CREATE TABLE IF NOT EXISTS robots (
    id UUID PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    status VARCHAR(50) NOT NULL,
    battery_level INT NOT NULL,
    current_location GEOGRAPHY(POINT, 4326),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS robots_location_idx ON robots USING GIST (current_location);

CREATE TABLE IF NOT EXISTS robot_slots (
    id UUID PRIMARY KEY,
    robot_id UUID NOT NULL REFERENCES robots(id),
    slot_number INT NOT NULL,
    status VARCHAR(50) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
